steps:
  # Step 0: Setup SSH with private key from Secret Manager
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: bash
    secretEnv: ['SSH_KEY']
    args:
      - -c
      - |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

  # Step 1: Build all Docker services using docker-compose
  - name: 'gcr.io/cloud-builders/docker'
    dir: .
    args: ['compose', '-f', 'docker-compose.yml', 'build']

  # Step 2: SSH into the VM, pull latest code, and restart containers
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud compute ssh harshvardhanthosar@instance-20250401-134435 \
          --zone=us-central1-b \
          --command="cd /home/harshvardhanthosar/celia-backend-poc && git pull && docker compose up --build -d"

timeout: 1200s  # 20 minutes

options:
  logging: CLOUD_LOGGING_ONLY

secrets:
- secretEnv:
    SSH_KEY: projects/celia-backend/secrets/GITHUB_SSH_PRIVATE_KEY/versions/latest