services:
  postgres:
    image: postgres:15
    container_name: keycloak-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-server
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
    ports:
      - '${KEYCLOAK_PORT}:8080'
    command:
      [
        'start-dev',
        '--log-level=info',
        '--https-port=8443',
        '--hostname-strict=false',
      ]

  poc-server:
    build: .
    container_name: poc-server
    restart: always
    depends_on:
      - keycloak
    env_file:
      - .env
    environment:
      NODE_ENV: production
      MONGO_URI: ${MONGO_URI}
      MONGO_DATABASE: ${MONGO_DATABASE}
    ports:
      - '3000:3000'

  python-task-score:
    build: python-based-task-score-calculator
    container_name: python-task-score
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DATABASE: ${MONGO_DATABASE}
    ports:
      - '8000:8000'

volumes:
  keycloak_data:
