# docker-compose.live.yml
services:
  keycloak:
    environment:
      KC_HOSTNAME: auth.celia.run.place
      KC_HOSTNAME_STRICT: true
      KC_PROXY_HEADERS: xforwarded
    command:
      [
        'start-dev',
        '--log-level=info',
        '--cache=local',
        '--hostname=auth.celia.run.place',
        '--hostname-strict=true'
      ]

  poc-server:
    environment:
      KEYCLOAK_URL: 'http://keycloak:8080'