# docker-compose.live.yml
services:
  keycloak:
    command:
      [
        'start-dev',
        '--log-level=info',
        '--cache=local',
        '--proxy=edge',
        '--hostname=auth.celia.run.place',
        '--hostname-strict=false',
        '--hostname-port-stripping=true'
      ]

  poc-server:
    environment:
      KEYCLOAK_URL: 'http://keycloak:8080'
