services:
  postgres:
    image: postgres:15
    container_name: keycloak-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-server
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '${KEYCLOAK_PORT}:8080'
    command:
      [
        'start-dev',
        '--log-level=info',
        '--cache=local',
        '--spi-theme-cache-themes=false',
        '--spi-theme-static-max-age=-1',
        '--spi-theme-cache-templates=false',
        '--hostname-strict=false',
      ]

  poc-server:
    build: .
    container_name: poc-server
    restart: always
    depends_on:
      - keycloak
      - python-task-score
    env_file:
      - .env
    environment:
      NODE_ENV: development
      MONGO_URI: ${MONGO_URI}
      MONGO_DATABASE: ${MONGO_DATABASE}
      KEYCLOAK_URL: 'http://keycloak-server:8080'
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app # Mount local code into the container
      - /usr/src/app/node_modules # Ignore node_modules (keep dependencies inside the container)
    command: npm run start:dev # Hot reload enabled

  python-task-score:
    build: python-based-task-score-calculator
    container_name: python-task-score
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DATABASE: ${MONGO_DATABASE}
    command:
      ['uvicorn', 'main:app', '--host', '0.0.0.0', '--port', '8000', '--reload']
    ports:
      - '8000:8000'

volumes:
  keycloak_data:
