# app/constants.py

DEFAULT_SKILL_SCORE=0

MIN_VOLUNTEERS_REQUIRED=1
MAX_VOLUNTEERS_REQUIRED=8

MIN_RATING=1
MAX_RATING=5

MIN_HOURS_REQUIRED_PER_DAY=1
MAX_HOURS_REQUIRED_PER_DAY=6

ROUNDING_FACTOR=100
SKILL_COMPLEXITY_FACTOR=10
VOLUNTEERING_FACTOR=20
DURATION_FACTOR=40
DESCRIPTION_COMPLEXITY_FACTOR=10
RANDOM_HOOK_FACTOR=20

DEFAULT_PAGE_NUMBER=0
DEFAULT_PAGE_SIZE=10

ALLOWED_MEDIA_TYPES = {"image/jpeg", "image/png", "image/gif", "video/mp4", "video/mpeg", "video/quicktime"}
MAX_FILE_SIZE = 10 * 1024 * 1024  # 10MB limit